"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import ez_setup
ez_setup.use_setuptools()
from setuptools import setup

APP = ['apk_mass_install.py']
DATA_FILES = ['adb', 'aapt', 'backup.db']
PKGS = ['Crypto']
OPTIONS = {'argv_emulation': True,
           'packages' : PKGS}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
